Controllers/MessengerCreateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Notification_System.Controllers
{
    public class MessengerCreateController : Controller
    {
        [Authorize(Roles = "MessengerCreator,Admin")]
        public IActionResult Index()
        {
            ViewData["ShowSideBarBlock"] = true;
            return View();
        }
    }
}

Controllers/UserCreateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Notification_System.Controllers
{
    public class UserCreateController : Controller
    {
        [Authorize(Roles = "UserCreator,Admin")]
        public IActionResult Index()
        {
            ViewData["ShowSideBarBlock"] = true;
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
  
<body>
    <div class="container">
        @if (ViewData["ShowSideBarBlock"] != null && (bool)ViewData["ShowSideBarBlock"])
        {
            @*Боковое меню*@
            <div class="sidebar">
                <div class="top-button">
                    <a asp-controller="Account" asp-action="Index">
                        <button class="menu-item top-item" id="account">
                            <p>Аккаунт</p>
                            <img src="~/content/images/account/account.png" alt="account" />
                        </button>
                    </a>
                    <hr />
                    <a asp-controller="Setting" asp-action="Index">
                        <button class="menu-item top-item" id="settings">
                            <p>Настройки</p>
                            <img src="~/content/images/account/setting.png" alt="setting" />
                        </button>
                    </a>
                    <hr />
                    @if (User.IsInRole("UserCreator") || User.IsInRole("Admin"))
                    {
                        <a asp-controller="UserCreate" asp-action="Index">
                            <button class="menu-item top-item" id="settings">
                                <p>Новый пользователь</p>
                                <img src="~/content/images/account/setting.png" alt="setting" />
                            </button>
                        </a>
                        <hr />
                    }
                    @if (User.IsInRole("MessengerCreator") || User.IsInRole("Admin"))
                    {
                        <a asp-controller="MessengerCreate" asp-action="Index">
                            <button class="menu-item top-item" id="messengers">
                                <p>Мессенджеры</p>
                                <img src="@Url.Content("~/content/images/account/messenger.png")" alt="messengers" />
                            </button>
                        </a>
                        <hr />
                    }
                </div>

                <div class="bottom-button">
                    <hr />
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form asp-controller="Authorisation" asp-action="Exite" method="post">
                            <button class="menu-item bottom-item" id="exite">
                                <p>Выход</p>
                                <img src="~/content/images/account/exite.png" alt="exite" />
                            </button>
                        </form>
                    }
                    <hr />
                </div>
            </div>
        }
        
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="/js/change_style.js"></script>
</body>
</html>